### PR TITLE
Migrates library to .NETStandard 1.3

### PR DESCRIPTION
**Pull request by conniey**
* Required for testing in GitVersion.Core for .NET Standard (https://github.com/GitTools/GitTools.Core/issues/40)
* **TODO**: Replace Libgit2Sharp.Portable with LibGit2Sharp that supports .NET Standard when the package is created from: https://github.com/libgit2/libgit2sharp/pull/1318

### CODE REVIEW

**Comment by dazinator** [comment]
Is anyone able to merge this so that it can unblock upstream PR's?

**Comment by asbjornu** [comment]
@dazinator: Done!

**Comment by dazinator** [comment]
Amazeballs!

**Comment by dazinator** [comment]
@asbjornu - has this been released to nuget? The [appveyor build](https://ci.appveyor.com/project/GitTools/gittools-testing/branch/master/artifacts) has 1.1.1-beta0001 as an artifact, yet that nuget package dates back to 22nd april on the nuget page: https://www.nuget.org/packages/GitTools.Testing/1.1.1-beta0001

**Comment by asbjornu** [comment]
@dazinator: I assume we need something like GitTools/GitTools.Core@e76c34f912059b2189dd4be248e0d935aa8418b4 for `GitTools.Testing` as well.

**Pull request merged**
