### PR TITLE
closes #14 - publish nuget package on appveyor build.

### LINKED ISSUE #14: Nuget publish
Builds not currently automatically publishing to nuget. Need to add that magic section to appveyor.yml

### PR DESCRIPTION
**Pull request by dazinator**

### CODE REVIEW

**Comment by dazinator** [comment]
Well.. I tried to squash these changes, and it looks like it failed dismally.

I did

`git rebase -i HEAD~12`
The I changed `pick` to `squash` for all of the commits listed except one.
Then I tried to complete the operation and got a merge conflict.
Then I resolved the conflict and it showed commits to pull and push - I synced and.. bam still all the commits listed!

**Comment by dazinator** [comment]
This was a right pain.. @asbjornu I have added the nuget publish section but it doesn't appear to be running for some reason: https://ci.appveyor.com/project/GitTools/gittools-testing

Is there some appveyor setting that prevents deployments form running on PR branches?

Also my commit history is a bit of a joke, as things were working locally for me, but not on the appveyor server, so i kept having to make tweak after tweak trying to figure out what was wrong.

**Comment by asbjornu** [comment]
> Then I resolved the conflict and it showed commits to pull and push - I synced and.. bam still all the commits listed!

Yea, you shouldn't have pulled there. Whenever you change local history, remote history is dead to you and should be ignored. You need to get local history as you want it and then do `git push --force` to have the remote history overwritten too.

What `git pull` usually does is `git fetch <remote> && git rebase <remote/branch>` or `git merge <remote/branch>`. That `rebase` or `merge` will then have outdated commits in the remotes rebased or merged into your local branch.

If you want to get back to your squashed commit, you can just do `git reset --hard <sha>`. You should have that SHA in your branch already. If not, you should find it in `git reflog`. When you've reset your local branch, ensure it is working as intended and do `git push --force`.

> Is there some appveyor setting that prevents deployments form running on PR branches?

Perhaps `disable_publish_on_pr: true` is the default? I don't know.

**Comment by dazinator** [comment]
Oh right. Thanks for the explaination, i'll give it another go.

Wasnt aware of such a flag but i'll look into it! Do we want pr's to be published?

**Comment by asbjornu** [comment]
> Oh right. Thanks for the explaination, i'll give it another go.

👍 

> Wasnt aware of such a flag but i'll look into it! Do we want pr's to be published?

No, I don't think we do. 😃

**Comment by dazinator** [comment]
Think this can be merged now...

**Comment by dazinator** [comment]
Thanks

**Pull request merged**
