### PR TITLE
Update and rename GitVersionConfig.yaml to GitVersion.yml

### PR DESCRIPTION
**Pull request by dazinator**

### CODE REVIEW

**Comment by dazinator** [comment]
fixes #16

**Comment by dazinator** [comment]
@asbjornu another one for you to merge :-)

**Comment by asbjornu** [comment]
Not very important, but the rename was not detected as a rename. Would it be too much to ask that you perform the rename and `beta` removal in two different commits? 😄

**Comment by dazinator** [comment]
Hmm maybe its because I did this all through github.. I can try.

**Pull request closed without merging**
